### ISSUE TITLE
[Registration] Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Squadz** [lindgr3n/breeze-sveltekit#2] opened 2022-09-26 13:14 UTC
Hey,
I hope you are doing well.

**STEPS TO REPRODUCE**
```
laravel new backend
cd backend
composer require laravel/breeze
php artisan breeze:install api
php artisan migrate
git clone https://github.com/lindgr3n/breeze-sveltekit.git
mv breeze-sveltekit/ frontend/
npm install
npm run dev
```
Open http://localhost:3000/register
Try to create a new user

**OBSERVED RESULT**
Response 500 - 
```
Cannot convert undefined or null to object

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at /home/squadz/Projects/myProject/frontend/src/routes/api/register.ts:25:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async post (/home/squadz/Projects/myProject/frontend/src/routes/api/register.ts:10:22)
    at async render_endpoint (file:///home/squadz/Projects/myProject/frontend/.svelte-kit/runtime/server/index.js:127:19)
    at async resolve (file:///home/squadz/Projects/myProject/frontend/.svelte-kit/runtime/server/index.js:2579:11)
    at async Object.handle (/home/squadz/Projects/myProject/frontend/src/hooks.ts:37:18)
    at async respond (file:///home/squadz/Projects/myProject/frontend/.svelte-kit/runtime/server/index.js:2513:20)
    at async file:///home/squadz/Projects/myProject/frontend/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
```
**EXPECTED RESULT**
The user is created

**FRAMEWORK VERSIONS**
Laravel "9.31.0"
Php 8

**Comment by Squadz** [comment] 2022-09-26 16:46
**Update**
I tested this frontend with "breeze-backend-api", same issue.

It seems to be a route issue

web.php | https://github.com/lindgr3n/breeze-backend-api/blob/main/routes/web.php
```
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return ['Laravel' => app()->version()];
});

require __DIR__.'/auth.php';
```

**Comment by lindgr3n** [comment] 2022-09-28 09:19
Hi!
Thanks for reporting. Will try and see if I can reproduce it tonight or tomorrow.

**Comment by lindgr3n** [comment] 2022-09-29 17:27
Hi!
Did manage to try this now. Did you run the migrations on your backend?
In your backend make sure you have a database setup and have run the migrations like noted in https://laravel.com/docs/9.x/installation#databases-and-migrations

Second looks like there was an issue with not passing the password confirmation field. Pushed a fix for that. Strange that I did not notice it before.

Hope it helps.

**Closed as completed** 2022-10-17 19:31 UTC

**Comment by jakecausier** [comment] 2023-04-20 22:47
I've found the root cause of this.

Setting your APP_NAME on the Laravel backend will cause the session cookie to be named differently to what the sveltekit is sending and checking with the server (for example, `foobar_session` from the backend will not play nice with the `laravel_session` key that the frontend has defined)

I manually fixed this on my repo by changing the keys in the cookie check to pull from my .env instead, much like how the axios baseUrl is performed.
